name: Create release

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    name: Build
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23.6

      - name: Get dependencies
        run: go mod download

      - name: Set environment variables
        run: |
          APP_VER_SHORT=$(git describe --tags --always)
          GOOS=$(go env GOOS)
          GOARCH=$(go env GOARCH)
          ARCHIVE="drt-go-oracles_${APP_VER_SHORT}_${GOOS}_${GOARCH}.tgz"
          ARTIFACT_NAME="drt-go-oracles_${GOOS}_${GOARCH}"
          BUILD_DIR=${GITHUB_WORKSPACE}/build

          echo "APP_VER_SHORT=${APP_VER_SHORT}" >> $GITHUB_ENV
          echo "GOOS=${GOOS}" >> $GITHUB_ENV
          echo "GOARCH=${GOARCH}" >> $GITHUB_ENV
          echo "ARCHIVE=${ARCHIVE}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
          echo "BUILD_DIR=${BUILD_DIR}" >> $GITHUB_ENV

      - name: Build
        run: |
          mkdir -p ${BUILD_DIR}
          cd ${GITHUB_WORKSPACE}/cmd/oracle && go build -o "${BUILD_DIR}/" -ldflags="-X main.appVersion=${{ env.APP_VER_SHORT }}"

      - name: Package
        run: |
          cd ${BUILD_DIR}
          tar czvf "${GITHUB_WORKSPACE}/${ARCHIVE}" *
          stat ${GITHUB_WORKSPACE}/${ARCHIVE}

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/${{ env.ARCHIVE }}
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: assets

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: assets

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --always)
          gh release delete ${TAG} --yes 2>/dev/null || true
          gh release create ${TAG} --draft \
            --title "Release draft from Github Actions" \
            --notes "" \
            $(find ./assets -name '*.tgz' -type f)
